name: Render Reel Video

on:
  workflow_dispatch:

permissions:
  contents: write # Allows creating/deleting Releases

jobs:
  render:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Ensure ffmpeg is available
        run: |
          if ! command -v ffmpeg &> /dev/null; then
            sudo apt update && sudo apt install -y ffmpeg
          else
            echo "ffmpeg is already installed"
          fi

      - name: Run script
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_RUN_ID: ${{ github.run_id }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }} # Add this in Repo Settings > Secrets
        run: |
          chmod +x script.sh
          ./script.sh
