name: Test GDrive Service Account

on: [push]

jobs:
  test-sa:
    runs-on: ubuntu-latest
    steps:
      - name: Install rclone
        run: sudo apt update && sudo apt install -y rclone

      - name: Create service account file
        run: echo "${{ secrets.GDRIVE_SERVICE_ACCOUNT }}" > /tmp/sa.json

      - name: Test GDrive
        run: rclone about gdrive: --drive-service-account-file /tmp/sa.json
